export const students = [
	{
		id: 1,
		firstName: "Arlana",
		lastName: "Connechie",
		email: "aconnechie0@a8.net",
		gender: "Male",
	},
	{
		id: 2,
		firstName: "Barn",
		lastName: "Kempson",
		email: "bkempson1@google.it",
		gender: "Male",
	},
	{
		id: 3,
		firstName: "Cyrille",
		lastName: "Ondrus",
		email: "condrus2@dagondesign.com",
		gender: "Male",
	},
	{
		id: 4,
		firstName: "Chaim",
		lastName: "Faltin",
		email: "cfaltin3@cafepress.com",
		gender: "Male",
	},
	{
		id: 5,
		firstName: "Andrey",
		lastName: "Kimblin",
		email: "akimblin4@issuu.com",
		gender: "Polygender",
	},
	{
		id: 6,
		firstName: "Breanne",
		lastName: "Eliet",
		email: "beliet5@ibm.com",
		gender: "Female",
	},
	{
		id: 7,
		firstName: "Dominique",
		lastName: "Orsay",
		email: "dorsay6@unblog.fr",
		gender: "Female",
	},
	{
		id: 8,
		firstName: "Margie",
		lastName: "Horsewood",
		email: "mhorsewood7@alibaba.com",
		gender: "Female",
	},
	{
		id: 9,
		firstName: "Desiree",
		lastName: "Adriaens",
		email: "dadriaens8@tripod.com",
		gender: "Male",
	},
	{
		id: 10,
		firstName: "Erie",
		lastName: "Longthorn",
		email: "elongthorn9@arizona.edu",
		gender: "Female",
	},
];
