name: Deploy Strapi to remote server

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - "server/cms/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: actions/checkout@v2
      - name: Deploy CMS
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          password: ${{secrets.SSH_PASSWORD}}
          username: ${{ secrets.SSH_USERNAME }}

          script: |
            cd app
            docker-compose pull cms
            docker-compose up -d cms
