name: Build and Push CMS to Docker hub

on:
  push:
    branches:
      - dev
    paths:
      - "cms/**"

jobs:
  build:
    name: Build Strapi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./cms
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/bdmis_cms:latest
